### ISSUE TITLE
What's the release process for this repo?

### ISSUE THREAD

**Issue by jameshfisher** [pusher/cide#22]
We say to install `cide` with `gem install cide`, which installs https://rubygems.org/gems/cide. But that Gem seems to be ambiguously owned - by Pusher or by @zimbatm ? I think we need to do one of

* confer with @zimbatm to get exclusive ownership of https://rubygems.org/gems/cide
* publish a new gem e.g. `gem install pusher-cide` and update our install instructions
* stop using `cide`

**Comment by jameshfisher** [comment]
cc @WillSewell

**Comment by jameshfisher** [comment]
Ah, I think I've misunderstood - we MOVED github.com/zimbatm/cide here, rather than forking it. So the upstream repo for https://rubygems.org/gems/cide is unambiguously this one.

**Comment by WillSewell** [comment]
Yep
